services:
  app:
    hostname: app
    networks:
      - mynet
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      MYSQL_PORT: 3306
    working_dir: /app
    build: ./app
    depends_on:
      - mysql
        #volumes:
        #- ./app:/app
    restart: always

  mysql:
    image: mariadb:latest
    hostname: mysql
    networks:
      - mynet
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 33060:33060
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql

#volumes:
  #todo-mysql-data:
networks:
  mynet:
    driver: bridge
