services:
  app:
    hostname: app
    networks:
      - mynet
    volumes:
      - ./front:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      MYSQL_PORT: 3306
    working_dir: /app
    build: ./front
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    hostname: db
    networks:
      - mynet
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql

volumes:
  todo-mysql-data:
networks:
  mynet:
    driver: bridge
